[base]
mission = "test.VR"
parameters = [
    "-noPauseAudio",
    "-noPause",
    "-window",
]

[default]
extends = "base"
workshop = [
    "450814997",  # CBA_A3's Workshop ID
    "463939057",  # ACE3
    "3499977893", # Advanced Developer Tools
    "1779063631", # ZEN
]

dlc = []
optionals = []

[ws]
dlc = ["ws"]
extends = "default"

[nomods]
extends = "base"